[project]
name = "Finance-Dashboard"
version = "2.0"
description = "A simple dashboard for reviewing your finances."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=2.18.2",
    "pandas>=2.2.3",
]
